### ISSUE TITLE
feat: Create sink-connectors repo and add atleast one sink with one abstraction 

### ISSUE THREAD

**Issue by gauravsinghania** [odpf/dagger#126]
**Context:**
As a first task, we want to create a repo which will hold the sink-connector library. This library will be used by both firehose and dagger. it might be private in the beginning until completed. 

**Acceptance criteria:**

- Define the abstraction for the interfaces.

- Implement influx db sink as a common library, as it is part of both firehose and dagger and it does not require batching in dagger side in the current implementation. 

- the library should provide way to plug in instrumentation for both firehose and dagger.

Out of scope: 

Implementation of a sink on dagger and/or firehose. We will do it in the next ticket.

**Comment by ravisuhag** [comment]
This is covered as part @odpf/depot repo.
