### ISSUE TITLE
Add support for JSON data

### ISSUE THREAD

**Issue by prakharmathur82** [odpf/dagger#53]
Currently, Dagger only supports SerDe for Protobuf encoded messages.

* JSON SerDe is already supported in Flink. Add support for enabling it.
* Apart from SerDe, postprocessors, preprocessors, some functions like ElementAt, HashTransformer also rely on Dynamic Message APIs. Need to ensure they work for JSON data as well.

**Comment by ravisuhag** [comment]
Stencil also soon plans to add support for JSON schemas. So, we would also need to consider how to integrate with the schema registry.
