### ISSUE TITLE
Use odpf stencil client

### ISSUE THREAD

**Issue by prakharmathur82** [odpf/dagger#60]
Dagger currently uses `com.gojek.stencil`, which is now being deprecated. Change it to use `'io.odpf.stencil` from [here](https://github.com/odpf/stencil).

**Comment by gauravsinghania** [comment]
Acceptance Criteria:

- Change the stencil client to use the latest version from ODPF
- Ensure the refresh is not enabled
- Default values are reasonable with proper timeouts
