### ISSUE TITLE
Dagger test case are failing in EsResponseHandlerTest while setting it up locally ./gradlew clean build 

### ISSUE THREAD

**Issue by shubhangi-1** [odpf/dagger#84]
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldCompleteResultFutureWithInputForPrimitiveData FAILED
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldCompleteResultFutureExceptionallyWhenPathDoesNotExists FAILED
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldHandleParseExceptionAndReturnInput FAILED
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldNotPopulateResultAsObjectIfTypeIsNotPassedAndRetainResponseTypeIsFalse FAILED
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldCompleteResultFutureWithInput FAILED
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldHandleIOExceptionAndReturnInput FAILED
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldHandleExceptionAndReturnInput FAILED
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldCompleteResultFutureWithInputAsObjectIfTypeIsNotPassedAndRetainResponseTypeIsTrue FAILED
io.odpf.dagger.core.processors.external.es.EsResponseHandlerTest > shouldHandleResponseParsingIOExceptionAndReturnInput FAILED

**Comment by arujit** [comment]
Hey @shubhangi-1 can you please try adding this config for test argument in build.gradle. It fixed this issue in my local. Adding this patch in the next release.
```
test {
    finalizedBy jacocoTestReport
    jvmArgs '-Djdk.attach.allowAttachSelf=true'
    testLogging {
        events "passed", "skipped", "failed"
    }
}```
